import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/styles.css";
import Header from "@/ui/header/header";
import Providers from "./providers";
import { Toaster } from "react-hot-toast";

const interFont = Inter({
  display: "swap",
  subsets: ["latin"],
  variable: "--font-main",
});

export const interFontClass = interFont.variable;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${interFont.variable} font-sans`}>
      <body>
        <Providers>
          <Toaster />
          <Header />
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
